ProductosClientesMVC/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using ProductosClientesMVC.Models.Request;
using ProductosClientesMVC.Models.Response;
using System.Text;
using System.Text.Json;

namespace ProductosClientesMVC.Controllers
{
    public class ClientesController : Controller
    {
        string url = "https://localhost:7104/api/Clientes";

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetAsync(string? filtro)
       {
            try
            {
                HttpClient client = new HttpClient();
                url = url + "?filtro=" + filtro;
                

                HttpResponseMessage response = await client.GetAsync(url);

                List<ClienteResponseV1> clientes = null;

                if (response.IsSuccessStatusCode)
                {
                    string JsonResponse= await response.Content.ReadAsStringAsync();
                    clientes = JsonSerializer.Deserialize<List<ClienteResponseV1>>(JsonResponse,new JsonSerializerOptions { PropertyNameCaseInsensitive=true });
                }
                else
                {
                    return new JsonResult(new {success=false, message = $"Hubo un errror: {response.StatusCode}", icon = "error" });
                    clientes = new List<ClienteResponseV1>();
                }

                return Json(new {success=true,clientes= clientes });
            }
            catch (Exception)
            {
                return Json(new {success=false, message = "Error, Contáctese con el administrador", icon = "error" });   
            }
        }

        public async Task<JsonResult> CreateAsync(ClienteRequestV1 request)
        {
            try
            {
                using HttpClient httpClient= new HttpClient();
                String JsonRequest = JsonSerializer.Serialize(request);
                HttpContent content = new StringContent(JsonRequest,Encoding.UTF8,"application/json");
                HttpResponseMessage response= await httpClient.PostAsync(url, content);
                if (response.IsSuccessStatusCode) {
                    string JsonResponse=await response.Content.ReadAsStringAsync();
                    return new JsonResult(new { success = true, message = "Cliente registrado correctamente", icon = "success" });
                }
                else
                {
                    return new JsonResult(new { message = $"Hubo un errror: {response.StatusCode}", icon = "error" });
                }

            }
            catch (Exception)
            {
                return Json(new { message = "Error, Contáctese con el administrador", icon = "error" });
            }
        }


        public async Task<JsonResult> DeleteAsync(int id)
        {

            try
            {
                using HttpClient httpClient = new HttpClient();
                url = url + "?id=" + id;

                HttpResponseMessage response = await httpClient.DeleteAsync(url);

                if (response.IsSuccessStatusCode)
                {
                    string JsonResponse = await response.Content.ReadAsStringAsync();
                    return new JsonResult(new { success = true, message = "Cliente eliminado correctamente", icon = "success" });
                }
                else
                {
                    return new JsonResult(new { success = false, message = $"Hubo un errror: {response.StatusCode}", icon = "error" });
                }
            }
            catch (Exception)
            {
                return Json(new { success = false, message = "Error, Contáctese con el administrador", icon = "error" });
            }

        }


    }
}

ProductosClientesMVC/Controllers/ProductosController.cs
using Microsoft.AspNetCore.Mvc;
using ProductosClientesMVC.Models.Request;
using ProductosClientesMVC.Models.Response;
using System.Text;
using System.Text.Json;

namespace ProductosClientesMVC.Controllers
{
    public class ProductosController : Controller
    {
        string url = "https://localhost:7104/api/Productos";

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetAsync(string? filtro)
        {
            try
            {
                HttpClient client = new HttpClient();
                url = url + "?filtro=" + filtro;

                HttpResponseMessage response= await client.GetAsync(url);

                List<ProductoResponseV1> productos = null;

                if (response.IsSuccessStatusCode)
                {
                    string JsonResponse= await response.Content.ReadAsStringAsync();
                    productos = JsonSerializer.Deserialize<List<ProductoResponseV1>>(JsonResponse, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                }
                else
                {
                    return new JsonResult(new {success=false, message = $"Hubo un errror: {response.StatusCode}", icon = "error" });
                    productos = new List<ProductoResponseV1>(); 
                }
                return Json(new  {  success = true, productos = productos });
                //return Json(productos);
            }
            catch (Exception)
            {
                return Json(new {success=false, message = "Error, Contáctese con el administrador", icon = "error" });
            }
        }

        public async Task<JsonResult> CreateAsync(ProductoRequestV1 request)
        {
            try
            {
                using HttpClient httpClient = new HttpClient();
                string JsonRequest =JsonSerializer.Serialize(request);
                HttpContent content = new StringContent(JsonRequest, Encoding.UTF8, "application/json");
                HttpResponseMessage response= await httpClient.PostAsync(url, content);

                if (response.IsSuccessStatusCode)
                {
                    string JsonResponse = await response.Content.ReadAsStringAsync();
                    return new JsonResult(new {message = "Producto registrado correctamente",icon="success" });
                }
                else
                {
                    return new JsonResult(new { message = $"Hubo un errror: {response.StatusCode}", icon="error" });
                }
            }
            catch (Exception)
            {
                return Json(new { message = "Error, Contáctese con el administrador", icon = "error"});
            }
        }

        public async Task<JsonResult> DeleteAsync(int id)
        {

            try
            {
                using HttpClient httpClient = new HttpClient();
                url = url + "?id=" + id;

                HttpResponseMessage response = await httpClient.DeleteAsync(url);

                if (response.IsSuccessStatusCode)
                {
                    string JsonResponse = await response.Content.ReadAsStringAsync();
                    return new JsonResult(new {success=true, message = "Producto eliminado correctamente", icon = "success" });
                }
                else
                {
                    return new JsonResult(new {success=false, message = $"Hubo un errror: {response.StatusCode}", icon = "error" });
                }
            }
            catch (Exception)
            {
                return Json(new { success=false,message = "Error, Contáctese con el administrador", icon = "error" });
            }

        }

    }
}

ProductosClientesMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Productos-Clientes-MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductosClientesMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Productos-Clientes-MVC </br><span><strong>Santos Pairazamán Flores</strong></span></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                        </li   <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Productos-Clientes-MVC - Santos Pairazamán Flores.
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>

    <script src="~/lib/jquery-validation/dist/additional-methods.min.js"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>